group: travis_latest
language: python
cache: pip
python:
    - 3.6
    #- nightly
    #- pypy3
matrix:
    allow_failures:
        - python: nightly
        - python: pypy3
install:
    - pip install -r requirements.txt
    - pip install flake8  # pytest  # add another testing frameworks later
    - pip install python-coveralls
    - pip install coverage
    - pip install nose
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    # Check python install package
    - pip3 install -e .
    # Check unittest running
    - python3 -m unittest discover tests
    # Check pytest running
    - python3 -m pytest tests
    # Run nose with coverage support
    - nosetests --with-coverage
    # Check python uninstall package
    - pip3 uninstall -y algorithms
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down

after_success:
  - coveralls
